# Generated by Django 4.1.1 on 2022-09-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(null=True)),
                ('f_nac', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
